name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  go-tests:
    name: Go Tests
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: backend/go.mod
          fallback-go-version: '1.21'

      - name: Run Go unit tests
        working-directory: backend
        run: |
          if [ -f go.mod ]; then
            go test ./...
          else
            echo "No Go module found in backend/. Skipping Go tests."
          fi

  frontend-tests:
    name: Frontend Unit Tests
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: |
            frontend/package-lock.json
            frontend/pnpm-lock.yaml
            frontend/yarn.lock

      - name: Install dependencies and run tests
        working-directory: frontend
        run: |
          if [ -f package.json ]; then
            if [ -f pnpm-lock.yaml ]; then
              corepack enable pnpm
              pnpm install --frozen-lockfile
              pnpm test -- --watch=false
            elif [ -f package-lock.json ]; then
              npm ci
              npm test -- --watch=false
            elif [ -f yarn.lock ]; then
              corepack enable
              yarn install --immutable
              yarn test --watch=false
            else
              npm install
              npm test -- --watch=false
            fi
          else
            echo "No frontend/package.json found. Skipping frontend tests."

  lint:
    name: Lint
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '18'

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.21'

      - name: Run lint checks
        run: bash scripts/lint.sh
